"use client";

import { useState } from "react";
import {
  Twitter,
  Star,
  CheckCircle,
  XCircle,
  HelpCircle,
  TrendingUp,
  Sliders,
  Sparkles,
  Smartphone,
  Eye,
  Info,
  ShieldCheck,
  Award,
  ChevronRight,
  BookOpen,
  ArrowRight,
  MessageSquare,
  Users,
} from "lucide-react";

export function TwitterReviewGuide() {
  const [activeFaq, setActiveFaq] = useState<number | null>(null);

  const steps = [
    {
      step: "01",
      title: "Open the Twitter Review Tool",
      desc: "Visit the Twitter section of the generator to access the live tweet-style preview area.",
    },
    {
      step: "02",
      title: "Generate a Fake Twitter Review",
      desc: "Click the generate or refresh button to instantly create a new fake Twitter testimonial with random profile details and feedback.",
    },
    {
      step: "03",
      title: "Capture Your Tweet Mockup",
      desc: "When you find a result you like, take a screenshot of the review card and reuse it across mockups and design concepts.",
    },
  ];

  const features = [
    "Instant fake Twitter testimonial generation",
    "Realistic fake tweet review mockup layouts",
    "Natural-looking Twitter feedback text",
    "Mobile-friendly tweet review designs",
    "Refresh button for unlimited review variations",
    "Simple interface for quick screenshot creation",
    "Perfect for Figma, Sketch, Adobe XD, and presentations",
  ];

  const useCases = [
    {
      title: "UI & UX Design Projects",
      desc: "Fill social media-inspired interfaces with realistic tweet reviews to make mockups feel like finished products.",
      badge: "UI Design",
      color: "border-sky-200 bg-sky-50 text-sky-850",
    },
    {
      title: "Client & Marketing Presentations",
      desc: "Show how customer feedback and testimonials could appear in social media campaigns or branded designs.",
      badge: "Pitches",
      color: "border-blue-200 bg-blue-50 text-blue-800",
    },
    {
      title: "Front-End Development Testing",
      desc: "Test spacing, typography, responsiveness, and card layouts using realistic Twitter-style review content.",
      badge: "Testing",
      color: "border-cyan-250 bg-cyan-50 text-cyan-800",
    },
    {
      title: "Educational & Demo Projects",
      desc: "Use fake Twitter testimonials in tutorials, workshops, and classroom examples without needing real user data.",
      badge: "Education",
      color: "border-indigo-200 bg-indigo-50 text-indigo-800",
    },
  ];

  const faqs = [
    {
      q: "Is this tool connected to Twitter?",
      a: "No. This is an independent mockup and educational tool and is not affiliated with or endorsed by X.",
    },
    {
      q: "Are these Twitter reviews real?",
      a: "No. All reviews and testimonials generated by this tool are fictional and created only for mockups, demos, and educational projects.",
    },
    {
      q: "Can I use these tweet mockups in my portfolio?",
      a: "Yes. You can use them in presentations, UI case studies, and portfolio projects as sample or fictional content.",
    },
    {
      q: "Can I use this tool for real customer reviews?",
      a: "No. This tool should not be used to publish misleading or fake testimonials on real platforms.",
    },
  ];

  return (
    <div className="space-y-16 py-12 px-4 sm:px-6 lg:px-8 max-w-6xl mx-auto">
      
      {/* Hero Banner with Twitter Sky Blue Styling */}
      <div className="relative overflow-hidden rounded-3xl bg-gradient-to-tr from-sky-950 via-[#1DA1F2]/20 to-blue-950 p-8 sm:p-12 shadow-2xl">
        <div className="absolute inset-0 bg-black/40 mix-blend-overlay" />
        
        {/* Top brand header accent bar */}
        <div className="absolute top-0 left-0 w-full h-1.5 bg-[#1DA1F2]" />

        <div className="relative z-10 max-w-3xl text-white">
          <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-semibold bg-white/10 text-white border border-white/20 mb-6 uppercase tracking-wider">
            <Twitter size={13} className="text-[#1DA1F2] animate-pulse" /> Feedback Visualizer
          </span>
          <h2 className="text-3xl sm:text-4xl lg:text-5xl font-black text-white leading-tight tracking-tight mb-4">
            Twitter Review Generator
          </h2>
          <p className="text-base sm:text-lg text-white/90 leading-relaxed font-normal">
            Twitter has become one of the most recognizable platforms for public conversations, customer opinions, and brand feedback online. This fake Twitter review generator helps you instantly create believable Twitter-style feedback cards for demos, prototypes, portfolio projects, and educational use.
          </p>
        </div>
      </div>

      {/* Grid: What This Tool Does & Why Use Twitter Review Mockups */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 lg:gap-12 items-stretch">
        
        {/* What This Twitter Review Tool Does */}
        <div className="lg:col-span-6 bg-white rounded-2xl p-6 sm:p-8 shadow-sm border border-slate-100 flex flex-col justify-between">
          <div className="space-y-4">
            <div className="flex items-center gap-3">
              <div className="p-2.5 bg-sky-50 rounded-xl text-[#1DA1F2]">
                <Info size={20} />
              </div>
              <h3 className="text-xl font-bold text-slate-900">What This Twitter Feedback Generator Does</h3>
            </div>
            <p className="text-slate-600 text-sm sm:text-base leading-relaxed">
              This tool creates realistic Twitter-style review and testimonial mockups that look similar to genuine tweet conversations and feedback posts.
            </p>
            <p className="text-slate-500 text-xs font-semibold block uppercase tracking-wider text-slate-400">Included Mockup Details:</p>
            <div className="grid grid-cols-2 gap-3 text-slate-700 text-xs font-semibold">
              <div className="flex items-center gap-2">
                <CheckCircle size={14} className="text-[#1DA1F2]" /> Username and avatar
              </div>
              <div className="flex items-center gap-2">
                <CheckCircle size={14} className="text-[#1DA1F2]" /> Handle and profile formatting
              </div>
              <div className="flex items-center gap-2">
                <CheckCircle size={14} className="text-[#1DA1F2]" /> Tweet-style testimonial text
              </div>
              <div className="flex items-center gap-2">
                <CheckCircle size={14} className="text-[#1DA1F2]" /> Like/reply/repost indicators
              </div>
              <div className="flex items-center gap-2 text-wrap">
                <CheckCircle size={14} className="text-[#1DA1F2]" /> Realistic time labels
              </div>
            </div>
          </div>
        </div>

        {/* Why Use Twitter Review Mockups? */}
        <div className="lg:col-span-6 bg-slate-50 rounded-2xl p-6 sm:p-8 shadow-sm border border-slate-200/80 flex flex-col justify-between">
          <div className="space-y-4">
            <div className="flex items-center gap-3">
              <div className="p-2.5 bg-sky-50 rounded-xl text-[#1DA1F2]">
                <Sliders size={20} />
              </div>
              <h3 className="text-xl font-bold text-slate-900">Why Use Twitter Review Mockups?</h3>
            </div>
            <p className="text-slate-600 text-sm leading-relaxed">
              Fake Twitter testimonials are useful because they help designers and developers create interfaces that feel complete and realistic instead of empty.
            </p>
            <div className="space-y-3 pt-1">
              {[
                "Test how feedback text wraps on different screen sizes",
                "Preview social media layouts with realistic content",
                "Create polished portfolio and client presentations",
                "Replace placeholder text with natural-looking Twitter feedback",
                "Demonstrate realistic social proof designs in UI concepts",
              ].map((reason, idx) => (
                <div key={idx} className="flex gap-2.5 items-start">
                  <ChevronRight size={16} className="text-[#1DA1F2] mt-0.5 shrink-0" />
                  <span className="text-slate-700 text-xs sm:text-sm font-medium leading-snug">{reason}</span>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>

      {/* Steps: How to Use */}
      <div className="space-y-8">
        <div className="text-center max-w-2xl mx-auto space-y-2">
          <h3 className="text-2xl sm:text-3xl font-extrabold text-slate-900">
            How to Use the Fake Twitter Review Generator
          </h3>
          <p className="text-slate-500 text-sm">
            Quickly add high-quality visual social reviews to your workflows.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {steps.map((s, idx) => (
            <div key={idx} className="bg-white rounded-2xl p-6 border border-slate-100 shadow-sm flex flex-col justify-between hover:shadow-md transition-all">
              <span className="text-xs font-extrabold text-[#1DA1F2] uppercase tracking-widest block mb-4">Step {s.step}</span>
              <div className="space-y-2">
                <h4 className="font-bold text-slate-900 text-sm sm:text-base leading-snug">{s.title}</h4>
                <p className="text-slate-600 text-xs sm:text-sm leading-relaxed">{s.desc}</p>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Grid: Features & Target Audience */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 lg:gap-12 items-stretch">
        
        {/* Features */}
        <div className="lg:col-span-7 bg-white rounded-2xl p-6 sm:p-8 shadow-sm border border-slate-100 flex flex-col justify-between">
          <div className="space-y-5">
            <div className="flex items-center gap-3">
              <div className="p-2.5 bg-sky-50 rounded-xl text-[#1DA1F2]">
                <Sparkles size={20} />
              </div>
              <h3 className="text-xl font-bold text-slate-900">Features Of This Generator</h3>
            </div>
            
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 pt-1">
              {features.map((feat, idx) => (
                <div key={idx} className="flex gap-2 items-start">
                  <CheckCircle size={14} className="text-emerald-500 shrink-0 mt-0.5" />
                  <span className="text-slate-700 text-xs sm:text-sm font-medium leading-snug">{feat}</span>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Target Audience */}
        <div className="lg:col-span-5 bg-slate-50 rounded-2xl p-6 sm:p-8 shadow-sm border border-slate-200/80 flex flex-col justify-between">
          <div className="space-y-5">
            <div className="flex items-center gap-3">
              <div className="p-2.5 bg-blue-50 rounded-xl text-blue-600">
                <Users size={20} />
              </div>
              <h3 className="text-xl font-bold text-slate-900">Who This Generator Is For</h3>
            </div>
            
            <div className="space-y-4 pt-1">
              {[
                { title: "UI and UX Designers", desc: "Create polished social media mockups with believable tweet-style reviews." },
                { title: "Front-End Developers", desc: "Populate components and feeds with realistic Twitter feedback." },
                { title: "Students and Learners", desc: "Build portfolio projects and final presentations faster." },
                { title: "Content Creators & Educators", desc: "Add realistic Twitter-style visuals to tutorials and materials." },
              ].map((user, idx) => (
                <div key={idx} className="flex gap-3 items-start">
                  <div className="h-5 w-5 rounded-full bg-sky-50 text-[#1DA1F2] font-bold text-xs flex items-center justify-center shrink-0 mt-0.5">
                    {idx + 1}
                  </div>
                  <div className="space-y-0.5">
                    <h4 className="font-extrabold text-slate-900 text-xs sm:text-sm">{user.title}</h4>
                    <p className="text-slate-500 text-xs">{user.desc}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>

      {/* Grid: Use cases */}
      <div className="space-y-8">
        <div className="text-center max-w-2xl mx-auto space-y-2">
          <h3 className="text-2xl sm:text-3xl font-extrabold text-slate-900">
            Practical Ways to Use Fake Tweet Feedback
          </h3>
          <p className="text-slate-500 text-sm">
            Tweet review visuals fit perfectly across multiple visual and development design paths.
          </p>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
          {useCases.map((uc, idx) => (
            <div key={idx} className="bg-white rounded-2xl p-5 border border-slate-100 shadow-sm flex flex-col justify-between space-y-4 hover:-translate-y-1 transition-all duration-300">
              <div className="space-y-2">
                <span className={`inline-block text-[9px] font-bold uppercase tracking-wider px-2 py-0.5 rounded-full border ${uc.color}`}>
                  {uc.badge}
                </span>
                <h4 className="text-sm sm:text-base font-bold text-slate-900">{uc.title}</h4>
                <p className="text-slate-600 text-xs leading-relaxed">{uc.desc}</p>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Tips for better mockups */}
      <div className="bg-slate-950 text-white rounded-3xl p-6 sm:p-10 space-y-6 relative overflow-hidden">
        <div className="absolute top-0 right-0 w-64 h-64 bg-sky-500/10 rounded-full blur-3xl" />
        <div className="max-w-3xl space-y-4 relative z-10">
          <div className="flex items-center gap-2 text-[#1DA1F2]">
            <TrendingUp size={20} />
            <span className="font-extrabold text-xs uppercase tracking-wider">Tips for Better Mockups</span>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 pt-2 text-slate-300 text-xs sm:text-sm">
            <div className="flex items-start gap-2">
              <ChevronRight size={14} className="text-[#1DA1F2] shrink-0 mt-0.5" />
              <span>Use different review lengths to test responsive layouts.</span>
            </div>
            <div className="flex items-start gap-2">
              <ChevronRight size={14} className="text-[#1DA1F2] shrink-0 mt-0.5" />
              <span>Generate multiple tweet reviews for realistic feed designs.</span>
            </div>
            <div className="flex items-start gap-2">
              <ChevronRight size={14} className="text-[#1DA1F2] shrink-0 mt-0.5" />
              <span>Mix positive and neutral feedback for a more natural appearance.</span>
            </div>
            <div className="flex items-start gap-2">
              <ChevronRight size={14} className="text-[#1DA1F2] shrink-0 mt-0.5" />
              <span>Label exported visuals as “Mockup” or “Demo” when sharing publicly.</span>
            </div>
          </div>
        </div>
      </div>

      {/* Ethical warning */}
      <div className="bg-slate-50 border border-slate-200/80 rounded-2xl p-6 sm:p-8 flex flex-col sm:flex-row items-start gap-4 max-w-4xl mx-auto">
        <div className="p-3 bg-sky-50 text-[#1DA1F2] rounded-xl shrink-0">
          <ShieldCheck size={24} />
        </div>
        <div className="space-y-2">
          <h4 className="font-bold text-slate-900 text-base">Honest and Responsible Use</h4>
          <p className="text-slate-600 text-xs sm:text-sm leading-relaxed">
            This fake Twitter review generator is made for educational, design, and development purposes only. You should not use it for posting fake testimonials on real social platforms, misleading audiences, or pretending generated feedback is from real users.
          </p>
        </div>
      </div>

      {/* FAQ accordion */}
      <div className="space-y-8 bg-white border border-slate-200/80 rounded-3xl p-6 sm:p-10">
        <div className="text-center max-w-2xl mx-auto space-y-2">
          <h3 className="text-2xl sm:text-3xl font-extrabold text-slate-900">
            Frequently Asked Questions
          </h3>
          <p className="text-slate-500 text-sm">
            Everything you need to know about our fake Twitter review generator tool.
          </p>
        </div>

        <div className="max-w-3xl mx-auto space-y-4">
          {faqs.map((faq, idx) => (
            <div key={idx} className="border border-slate-200/60 rounded-xl overflow-hidden shadow-sm">
              <button
                onClick={() => setActiveFaq(activeFaq === idx ? null : idx)}
                className="w-full flex items-center justify-between p-4 bg-slate-50/50 hover:bg-slate-50 transition-colors text-left"
              >
                <span className="font-bold text-slate-900 text-sm sm:text-base leading-snug">{faq.q}</span>
                <HelpCircle size={18} className="text-slate-400 shrink-0 ml-2" />
              </button>
              
              {activeFaq === idx && (
                <div className="p-4 border-t border-slate-100 bg-white text-slate-600 text-xs sm:text-sm leading-relaxed">
                  {faq.a}
                </div>
              )}
            </div>
          ))}
        </div>
      </div>

    </div>
  );
}
