import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms and Conditions - ReviewCraft",
  description:
    "Terms and conditions for using ReviewCraft, an educational social media review generator. Please read our usage guidelines and legal terms.",
  openGraph: {
    title: "Terms and Conditions - ReviewCraft",
    description:
      "Terms and conditions for using ReviewCraft. Educational usage guidelines and legal terms.",
    url: "/terms",
    type: "website",
  },
};

const TermsPage = () => {
  return (
    <div className="min-h-screen bg-gray-50 py-12">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Header */}
        <div className="text-center mb-12">
          <h1 className="text-4xl md:text-5xl font-bold text-gray-900 mb-4">
            Terms and Conditions
          </h1>
          <p className="text-xl text-gray-600">
            Last updated: {new Date().toLocaleDateString()}
          </p>
        </div>

        {/* Main Content */}
        <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-8">
          <div className="prose prose-lg max-w-none">
            <h2 className="text-2xl font-bold text-gray-900 mb-4">
              1. Acceptance of Terms
            </h2>
            <p className="text-gray-600 mb-6">
              By accessing and using ReviewCraft ("the Service"), you accept and
              agree to be bound by the terms and provision of this agreement. If
              you do not agree to abide by the above, please do not use this
              service.
            </p>

            <h2 className="text-2xl font-bold text-gray-900 mb-4">
              2. Educational Purpose Only
            </h2>
            <p className="text-gray-600 mb-6">
              ReviewCraft is designed exclusively for educational purposes,
              design mockups, presentations, and learning activities. The
              Service generates simulated social media content that is clearly
              marked as artificial and should never be used to deceive or
              mislead users.
            </p>

            <h2 className="text-2xl font-bold text-gray-900 mb-4">
              3. Prohibited Uses
            </h2>
            <p className="text-gray-600 mb-4">
              You agree not to use the Service:
            </p>
            <ul className="text-gray-600 mb-6 space-y-2 pl-6">
              <li>• To create content intended to deceive or mislead others</li>
              <li>• To generate fake reviews for commercial purposes</li>
              <li>
                • To harm the reputation of individuals, businesses, or
                organizations
              </li>
              <li>• To violate any applicable laws or regulations</li>
              <li>• To infringe upon intellectual property rights of others</li>
              <li>• To harass, abuse, or harm another person</li>
              <li>• To impersonate any person or entity</li>
            </ul>

            <h2 className="text-2xl font-bold text-gray-900 mb-4">
              4. Content Disclaimer
            </h2>
            <p className="text-gray-600 mb-6">
              All content generated by ReviewCraft is artificial and simulated.
              User profiles, names, avatars, and review content are generated
              using external APIs and random data sources. Any resemblance to
              real persons, living or dead, or actual events is purely
              coincidental.
            </p>

            <h2 className="text-2xl font-bold text-gray-900 mb-4">
              5. Intellectual Property
            </h2>
            <p className="text-gray-600 mb-6">
              The Service and its original content, features, and functionality
              are and will remain the exclusive property of Abishek Khadka and
              its licensors. The Service is protected by copyright, trademark,
              and other laws. Generated content may be used according to these
              terms.
            </p>

            <h2 className="text-2xl font-bold text-gray-900 mb-4">
              6. User Responsibilities
            </h2>
            <p className="text-gray-600 mb-4">Users are responsible for:</p>
            <ul className="text-gray-600 mb-6 space-y-2 pl-6">
              <li>• Using the Service in accordance with these terms</li>
              <li>
                • Clearly marking generated content as simulated when sharing
              </li>
              <li>
                • Respecting the intellectual property rights of platform
                designs
              </li>
              <li>
                • Not attempting to reverse engineer or replicate the Service
              </li>
              <li>
                • Maintaining the educational and non-deceptive nature of usage
              </li>
            </ul>

            <h2 className="text-2xl font-bold text-gray-900 mb-4">
              7. Data Collection and Privacy
            </h2>
            <p className="text-gray-600 mb-6">
              We may collect anonymous usage data through Google Analytics to
              improve the Service. We do not collect personal information from
              users. Generated review content is not stored on our servers.
              External APIs used for user profile generation have their own
              privacy policies.
            </p>

            <h2 className="text-2xl font-bold text-gray-900 mb-4">
              8. Service Availability
            </h2>
            <p className="text-gray-600 mb-6">
              We strive to keep the Service available but make no guarantees
              about uptime or availability. The Service may be temporarily
              unavailable due to maintenance, updates, or technical issues. We
              reserve the right to modify or discontinue the Service at any
              time.
            </p>

            <h2 className="text-2xl font-bold text-gray-900 mb-4">
              9. Limitation of Liability
            </h2>
            <p className="text-gray-600 mb-6">
              In no event shall ReviewCraft, its creators, or contributors be
              liable for any indirect, incidental, special, consequential, or
              punitive damages, including without limitation, loss of profits,
              data, use, goodwill, or other intangible losses, resulting from
              your use of the Service.
            </p>

            <h2 className="text-2xl font-bold text-gray-900 mb-4">
              10. Platform Trademarks
            </h2>
            <p className="text-gray-600 mb-6">
              All social media platform names, logos, and designs referenced or
              replicated in this Service are trademarks of their respective
              owners. ReviewCraft is not affiliated with, endorsed by, or
              connected to any of these platforms. The replication of designs is
              for educational purposes only.
            </p>

            <h2 className="text-2xl font-bold text-gray-900 mb-4">
              11. Termination
            </h2>
            <p className="text-gray-600 mb-6">
              We may terminate or suspend access to our Service immediately,
              without prior notice or liability, for any reason whatsoever,
              including without limitation if you breach the Terms.
            </p>

            <h2 className="text-2xl font-bold text-gray-900 mb-4">
              12. Changes to Terms
            </h2>
            <p className="text-gray-600 mb-6">
              We reserve the right, at our sole discretion, to modify or replace
              these Terms at any time. If a revision is material, we will try to
              provide at least 30 days notice prior to any new terms taking
              effect.
            </p>

            <h2 className="text-2xl font-bold text-gray-900 mb-4">
              13. Governing Law
            </h2>
            <p className="text-gray-600 mb-6">
              These Terms shall be interpreted and governed by the laws of the
              jurisdiction in which the Service is operated, without regard to
              its conflict of law provisions.
            </p>

            <h2 className="text-2xl font-bold text-gray-900 mb-4">
              14. Contact Information
            </h2>
            <p className="text-gray-600 mb-6">
              If you have any questions about these Terms and Conditions, please
              contact us through our GitHub repository at:
              <a
                href="https://github.com/khadka27/review-craft"
                className="text-indigo-600 hover:text-indigo-800 ml-1"
                target="_blank"
                rel="noopener noreferrer"
              >
                https://github.com/khadka27/review-craft
              </a>
            </p>

            <div className="bg-blue-50 border border-blue-200 rounded-lg p-6 mt-8">
              <h3 className="text-lg font-semibold text-blue-900 mb-2">
                Important Reminder
              </h3>
              <p className="text-blue-800">
                ReviewCraft is designed for educational and demonstration
                purposes only. Always use the generated content responsibly and
                ensure it is clearly marked as simulated when shared with
                others.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default TermsPage;
