import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Disclaimer - ReviewCraft",
  description:
    "Disclaimer for ReviewCraft regarding educational-only usage, no affiliation with third-party platforms, and limitation of liability.",
  openGraph: {
    title: "Disclaimer - ReviewCraft",
    description:
      "Important legal disclaimer about educational use and non-affiliation.",
    url: "/disclaimer",
    type: "website",
  },
};

export default function DisclaimerPage() {
  return (
    <div className="min-h-screen bg-gray-50 py-12">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-10">
          <h1 className="text-4xl md:text-5xl font-bold text-gray-900 mb-3">
            Disclaimer
          </h1>
          <p className="text-lg text-gray-600">Last updated: {new Date().getFullYear()}-{String(new Date().getMonth() + 1).padStart(2, '0')}-{String(new Date().getDate()).padStart(2, '0')}</p>
        </div>

        <div className="bg-white rounded-xl border border-gray-200 shadow-sm p-8">
          <div className="space-y-6 text-gray-700 leading-7">
            <section>
              <h2 className="text-2xl font-semibold text-gray-900 mb-2">
                1. Educational Use Only
              </h2>
              <p>
                ReviewCraft is provided for educational, design, and
                presentation purposes. Content generated by this tool is
                simulated and should not be represented as authentic evidence or
                genuine customer opinion.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-gray-900 mb-2">
                2. No Platform Affiliation
              </h2>
              <p>
                ReviewCraft is not affiliated with, endorsed by, or sponsored by
                any social media, marketplace, or review platform referenced in
                templates.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-gray-900 mb-2">
                3. Content Responsibility
              </h2>
              <p>
                Users are solely responsible for how generated output is used
                and shared. You must comply with applicable laws, third-party
                terms, and ethical standards.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-gray-900 mb-2">
                4. Limitation of Liability
              </h2>
              <p>
                To the extent permitted by law, ReviewCraft and its contributors
                are not liable for losses or damages arising from misuse of
                generated content.
              </p>
            </section>
          </div>
        </div>
      </div>
    </div>
  );
}
